### ISSUE TITLE
Refactor dellemc_configure_idrac_users module to use state: present

### ISSUE THREAD

**Issue by tsquillario** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#24]
Refactor `dellemc_configure_idrac_users` module to use state: [present, absent] instead of action: [create, delete, modify]. Looking at the code you can check for the user and if it doesn't exist create it and if it does modify it.

This is a cleaner and more Ansible-y way to do things based on my experience. Otherwise I had to create two separate blocks one for create and one for modify. 

Would you like me to submit a pull request for this?

**Comment by anupamaloke** [comment]
@tsquillario, I agree with your suggestion. In fact, if you take a look at the ["dellemc_idrac_user"](https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC/blob/beta/library/dellemc_idrac_user.py) from the BETA branch, you can see that we were using the state: [present, absent]. 

If it is not a huge effort for you, could you please submit a pull request in our devel branch with your changes?

**Comment by tsquillario** [comment]
The beta branch is looking very similar to the changes I made. I'll switch to that!
