### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by feisa** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#3]
Hello, 

im receiving the following error when running my playbooks

setting up inventory plugins
Parsed /home/feisa/git/network/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: idrac_ntp_setup.yaml **************************************************************************************************************************************************************************************
1 plays in playbooks/idrac_ntp_setup.yaml

PLAY [idrac ntp configuration] **************************************************************************************************************************************************************************************
META: ran handlers

TASK [setting anycast ntp] ******************************************************************************************************************************************************************************************
task path: /home/feisa/git/network/playbooks/idrac_ntp_setup.yaml:7
<10.9.245.120> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.9.245.120> EXEC /bin/sh -c 'echo ~root && sleep 0'
<10.9.245.120> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745 `" && echo ansible-tmp-1532359842.63-3625996183745="` echo /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745 `" ) && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/dellemc/server/dellemc_configure_idrac_timezone.py
<10.9.245.120> PUT /root/.ansible/tmp/ansible-local-3217_eJwcQ/tmp_PCXNL TO /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745/dellemc_configure_idrac_timezone.py
<10.9.245.120> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745/ /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745/dellemc_configure_idrac_timezone.py && sleep 0'
<10.9.245.120> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745/dellemc_configure_idrac_timezone.py && sleep 0'
<10.9.245.120> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1532359842.63-3625996183745/ > /dev/null 2>&1 && sleep 0'
fatal: [10.9.245.120]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "enable_ntp": "Enabled", 
            "idrac": null, 
            "idrac_ip": "10.9.245.120", 
            "idrac_port": 443, 
            "idrac_pwd": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "idrac_user": "root", 
            "ntp_server_1": "10.255.255.2", 
            "ntp_server_2": null, 
            "ntp_server_3": null, 
            "setup_idrac_timezone": "UTC", 
            "share_mnt": "/mnt/tmp", 
            "share_name": "/mnt/tmp", 
            "share_pwd": null, 
            "share_user": null
        }
    }, 
    "msg": "'NoneType' object has no attribute 'local_full_path'"
}

PLAY RECAP **********************************************************************************************************************************************************************************************************
10.9.245.120               : ok=0    changed=0    unreachable=0    failed=1   

***********************

---
- name: idrac ntp configuration 
  hosts: idracs
  gather_facts: false
  connection: local
  tasks:
  - name: setting anycast ntp
    dellemc_configure_idrac_timezone:
     idrac_ip: 10.9.245.120 
     idrac_user: root
     idrac_pwd: *******
     share_name: /mnt/tmp
     share_mnt: /mnt/tmp
     enable_ntp: Enabled
     setup_idrac_timezone: UTC
     ntp_server_1: 10.255.255.2

**Comment by feisa** [comment]
I see my error there. Now I get 

fatal: [10.9.245.105]: FAILED! => {"changed": false, "msg": "'Status'"}
fatal: [10.9.245.110]: FAILED! => {"changed": false, "msg": "returned status code doesn't match with the expected success code"}
fatal: [10.9.245.113]: FAILED! => {"changed": false, "msg": "returned status code doesn't match with the expected success code"}
fatal: [10.9.245.116]: FAILED! => {"changed": false, "msg": "returned status code doesn't match with the expected success code"}
fatal: [10.9.245.120]: FAILED! => {"changed": false, "module_stderr": "WARNING: yacc table file version is out of date\nTraceback (most recent call last):\n  File \"/tmp/ansible_hayRKh/ansible_module_dellemc_configure_idrac_timezone.py\", line 262, in <module>\n    main()\n  File \"/tmp/ansible_hayRKh/ansible_module_dellemc_configure_idrac_timezone.py\", line 246, in main\n    idrac = idrac_conn.connect()\n  File \"/tmp/ansible_hayRKh/ansible_modlib.zip/ansible/module_utils/dellemc_idrac.py\", line 75, in connect\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkinfra.py\", line 137, in get_driver\n    return self._create_driver(mod, ipaddr, creds, protopref, pOptions)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkinfra.py\", line 156, in _create_driver\n    drv = self.disc_modules[mod].is_entitytype(self, ipaddr, creds, protopref, mod, pOptions)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkbase.py\", line 142, in is_entitytype\n    if entity.connect() :\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkbase.py\", line 245, in connect\n    return self.my_connect(pOptions)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkbase.py\", line 252, in my_connect\n    retval = self.cfactory.identify(self.entityjson)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkconnfactory.py\", line 100, in identify\n    self.enumerate_list(ejson, *self.pfactory.classifier)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkconnfactory.py\", line 191, in enumerate_list\n    comp_details = self.enumerate_view(comp)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkconnfactory.py\", line 126, in enumerate_view\n    retval = connection.enumerate_view(index, True)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkproto.py\", line 337, in enumerate_view\n    return self._enumerate_view(index, self.views, bTrue)\n  File \"/usr/lib/python2.7/site-packages/omsdk/sdkproto.py\", line 354, in _enumerate_view\n    retval = self.proto.enumerate(clsName, wsprof, self.selectors, False, filter)\n  File \"/usr/lib/python2.7/site-packages/omsdk/http/sdkredfishbase.py\", line 116, in enumerate\n    return self._communicate(clsName, resource)\n  File \"/usr/lib/python2.7/site-packages/omsdk/http/sdkredfishbase.py\", line 154, in _communicate\n    out = self._parse_output(clsName, resource)\n  File \"/usr/lib/python2.7/site-packages/omsdk/http/sdkredfishbase.py\", line 195, in _parse_output\n    memResponse = self.session.get(url, timeout=(self.pOptions.connection_timeout, self.pOptions.read_timeout))\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 525, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 512, in request\n    resp = self.send(prep, **send_kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 622, in send\n    r = adapter.send(request, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/adapters.py\", line 526, in send\n    raise ReadTimeout(e, request=request)\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='10.9.245.120', port=443): Read timed out. (read timeout=20)\n", "module_stdout": "2018-07-26 08:00:02,198 - INFO  - omsdk.omlogs.Logger:124 - Setting up Logging -- FINISHED\n2018-07-26 08:00:02,390 - INFO  - omdrivers.enums.iDRAC.iDRAC:242 - 10.9.245.120: CALLING: iDRAC Server Configuration\n2018-07-26 08:00:02,390 - INFO  - omdrivers.enums.iDRAC.iDRAC:244 - 10.9.245.120: CALLING: iDRAC Connection\n2018-07-26 08:00:02,391 - DEBUG - omsdk.sdkinfra:73 - Loading: 1::/usr/lib/python2.7/site-packages/omdrivers/emcScaleIO.py\n2018-07-26 08:00:02,391 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/emcScaleIO.py...\n2018-07-26 08:00:02,399 - INFO  - omsdk.sdkbase:113 - /usr/lib/python2.7/site-packages/omdrivers/emcScaleIO/emcScaleIO.Monitor does not exist!!\n2018-07-26 08:00:02,399 - DEBUG - omsdk.sdkinfra:73 - Loading: 2::/usr/lib/python2.7/site-packages/omdrivers/Printer.py\n2018-07-26 08:00:02,399 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/Printer.py...\n2018-07-26 08:00:02,400 - INFO  - omsdk.sdkbase:109 - Printer:: Loading defs\n2018-07-26 08:00:02,400 - DEBUG - omsdk.sdkinfra:73 - Loading: 3::/usr/lib/python2.7/site-packages/omdrivers/F10.py\n2018-07-26 08:00:02,400 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/F10.py...\n2018-07-26 08:00:02,402 - INFO  - omsdk.sdkbase:109 - F10:: Loading defs\n2018-07-26 08:00:02,402 - DEBUG - omsdk.sdkinfra:73 - Loading: 4::/usr/lib/python2.7/site-packages/omdrivers/Compellent.py\n2018-07-26 08:00:02,403 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/Compellent.py...\n2018-07-26 08:00:02,403 - INFO  - omsdk.sdkbase:109 - Compellent:: Loading defs\n2018-07-26 08:00:02,404 - DEBUG - omsdk.sdkinfra:73 - Loading: 5::/usr/lib/python2.7/site-packages/omdrivers/NSeries.py\n2018-07-26 08:00:02,404 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/NSeries.py...\n2018-07-26 08:00:02,405 - INFO  - omsdk.sdkbase:109 - NSeries:: Loading defs\n2018-07-26 08:00:02,405 - DEBUG - omsdk.sdkinfra:73 - Loading: 6::/usr/lib/python2.7/site-packages/omdrivers/FileList.py\n2018-07-26 08:00:02,405 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/FileList.py...\n2018-07-26 08:00:02,406 - INFO  - omsdk.sdkbase:113 - /usr/lib/python2.7/site-packages/omdrivers/FileList/FileList.Monitor does not exist!!\n2018-07-26 08:00:02,406 - DEBUG - omsdk.sdkinfra:73 - Loading: 7::/usr/lib/python2.7/site-packages/omdrivers/OME.py\n2018-07-26 08:00:02,406 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/OME.py...\n2018-07-26 08:00:02,406 - INFO  - omsdk.sdkbase:113 - /usr/lib/python2.7/site-packages/omdrivers/OME/OME.Monitor does not exist!!\n2018-07-26 08:00:02,407 - DEBUG - omsdk.sdkinfra:73 - Loading: 8::/usr/lib/python2.7/site-packages/omdrivers/MDArray.py\n2018-07-26 08:00:02,407 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/MDArray.py...\n2018-07-26 08:00:02,407 - INFO  - omsdk.sdkbase:109 - MDArray:: Loading defs\n2018-07-26 08:00:02,408 - DEBUG - omsdk.sdkinfra:73 - Loading: 9::/usr/lib/python2.7/site-packages/omdrivers/CMC.py\n2018-07-26 08:00:02,408 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/CMC.py...\n2018-07-26 08:00:02,410 - INFO  - omsdk.sdkbase:109 - CMC:: Loading defs\n2018-07-26 08:00:02,410 - DEBUG - omsdk.sdkinfra:73 - Loading: 10::/usr/lib/python2.7/site-packages/omdrivers/Nagios.py\n2018-07-26 08:00:02,410 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/Nagios.py...\n2018-07-26 08:00:02,411 - INFO  - omsdk.sdkbase:113 - /usr/lib/python2.7/site-packages/omdrivers/Nagios/Nagios.Monitor does not exist!!\n2018-07-26 08:00:02,411 - DEBUG - omsdk.sdkinfra:73 - Loading: 11::/usr/lib/python2.7/site-packages/omdrivers/iDRAC.py\n2018-07-26 08:00:02,411 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/iDRAC.py...\n2018-07-26 08:00:02,567 - INFO  - omsdk.sdkbase:109 - iDRAC:: Loading defs\n2018-07-26 08:00:02,568 - DEBUG - omsdk.sdkinfra:73 - Loading: 12::/usr/lib/python2.7/site-packages/omdrivers/emcViper.py\n2018-07-26 08:00:02,568 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/emcViper.py...\n2018-07-26 08:00:02,569 - INFO  - omsdk.sdkbase:113 - /usr/lib/python2.7/site-packages/omdrivers/emcViper/emcViper.Monitor does not exist!!\n2018-07-26 08:00:02,570 - DEBUG - omsdk.sdkinfra:73 - Loading: 13::/usr/lib/python2.7/site-packages/omdrivers/EqualLogic.py\n2018-07-26 08:00:02,570 - DEBUG - omsdk.sdkinfra:45 - Loading /usr/lib/python2.7/site-packages/omdrivers/EqualLogic.py...\n2018-07-26 08:00:02,571 - INFO  - omsdk.sdkbase:109 - EqualLogic:: Loading defs\n2018-07-26 08:00:02,572 - DEBUG - omsdk.sdkinfra:136 - get_driver(): Asking for iDRAC\n2018-07-26 08:00:02,573 - DEBUG - omsdk.sdkinfra:140 - get_driver(): Asking for iDRAC\n2018-07-26 08:00:02,573 - DEBUG - omsdk.sdkinfra:155 - iDRAC driver found!\n2018-07-26 08:00:02,573 - DEBUG - omsdk.sdkbase:782 - ERROR: _scp_export has additional argmethod\n2018-07-26 08:00:02,573 - DEBUG - omsdk.sdkbase:787 - ERROR: _scp_export different argument type\n2018-07-26 08:00:02,573 - DEBUG - omsdk.sdkbase:782 - ERROR: _scp_export has additional argformat_file\n2018-07-26 08:00:02,573 - DEBUG - omsdk.sdkbase:789 - ERROR: _scp_export different # of arguments across protocols!\n2018-07-26 08:00:02,574 - DEBUG - omsdk.sdkbase:787 - ERROR: _scp_import different argument type\n2018-07-26 08:00:02,574 - DEBUG - omsdk.sdkbase:782 - ERROR: _scp_import has additional argformat_file\n2018-07-26 08:00:02,574 - DEBUG - omsdk.sdkbase:789 - ERROR: _scp_import different # of arguments across protocols!\n2018-07-26 08:00:03,678 - DEBUG - omsdk.sdkconnfactory:77 - Connecting to iDRAC::proto(ProtocolEnum.WSMAN) for 0th time...\n2018-07-26 08:00:03,678 - DEBUG - omsdk.sdkproto:181 - Connecting to 10.9.245.120 using User(username=root)\n2018-07-26 08:00:03,678 - DEBUG - omsdk.sdkconnfactory:80 - iDRAC::connect(10.9.245.120, proto(ProtocolEnum.WSMAN))=True\n2018-07-26 08:00:03,678 - DEBUG - omsdk.sdkconnfactory:77 - Connecting to iDRAC::proto(ProtocolEnum.REDFISH) for 0th time...\n2018-07-26 08:00:03,679 - DEBUG - omsdk.sdkproto:181 - Connecting to 10.9.245.120 using User(username=root)\n2018-07-26 08:00:03,679 - DEBUG - omsdk.sdkproto:193 - Invalid pOptions provided!\n2018-07-26 08:00:03,679 - DEBUG - omsdk.sdkconnfactory:80 - iDRAC::connect(10.9.245.120, proto(ProtocolEnum.REDFISH))=True\n2018-07-26 08:00:03,679 - DEBUG - omsdk.sdkconnfactory:77 - Connecting to iDRAC::proto(ProtocolEnum.SNMP) for 0th time...\n2018-07-26 08:00:03,680 - DEBUG - omsdk.sdkproto:177 - Invalid credentials provided!\n2018-07-26 08:00:03,680 - DEBUG - omsdk.sdkconnfactory:83 - Connection failed to 10.9.245.120\n2018-07-26 08:00:03,680 - DEBUG - omsdk.sdkproto:344 - Collecting System ... via ProtocolEnum.WSMAN...\n2018-07-26 08:00:03,680 - DEBUG - omsdk.http.sdkhttpep:98 - Attempting a connection to device\n2018-07-26 08:00:03,680 - DEBUG - urllib3.util.retry:210 - Converted retries value: 1 -> Retry(total=1, connect=None, read=None, redirect=None, status=None)\n2018-07-26 08:00:03,681 - DEBUG - omsdk.http.sdkhttpep:114 - Connection to device: complete\n2018-07-26 08:00:03,681 - DEBUG - omsdk.http.sdkhttpep:119 - Begin doing HTTP POST with SOAP message\n2018-07-26 08:00:03,682 - DEBUG - omsdk.http.sdkhttpep:132 - Finished preparing POST request\n2018-07-26 08:00:03,682 - DEBUG - omsdk.http.sdkhttpep:135 - Begin submitting POST request\n2018-07-26 08:00:03,682 - DEBUG - urllib3.connectionpool:823 - Starting new HTTPS connection (1): 10.9.245.120:443\n2018-07-26 08:00:23,705 - DEBUG - omsdk.http.sdkhttpep:145 - HTTP Timeout error\n2018-07-26 08:00:23,705 - DEBUG - omsdk.http.sdkwsmanbase:436 - HTTP Timeout error\n2018-07-26 08:00:23,706 - DEBUG - omsdk.http.sdkwsmanbase:440 - <?xml version='1.0' encoding='utf8'?>\n<env:Envelope xmlns:a=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:b=\"http://schemas.dmtf.org/wbem/wsman/1/cimbinding.xsd\" xmlns:enc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:n=\"http://schemas.xmlsoap.org/ws/2004/09/enumeration\" xmlns:p=\"http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd\" xmlns:tns=\"http://schemas.microsoft.com/wmx/2005/06\" xmlns:w=\"http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd\" xmlns:wse=\"http://schemas.xmlsoap.org/ws/2004/08/eventing\" xmlns:wsmid=\"http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd\" xmlns:x=\"http://schemas.xmlsoap.org/ws/2004/09/transfer\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"><env:Header /><env:Body><ClientFault><Reason><Text>HTTP Timeout error</Text></Reason></ClientFault></env:Body></env:Envelope>\n2018-07-26 08:00:23,708 - DEBUG - omsdk.http.sdkwsmanbase:443 - {\n    \"Fault.Data\": {\n        \"Reason\": {\n            \"Text\": \"HTTP Timeout error\"\n        }\n    },\n    \"Message\": \"HTTP Timeout error\",\n    \"Status\": \"Found Client (SDK) Side Fault\"\n}\n2018-07-26 08:00:23,708 - DEBUG - omsdk.sdkproto:344 - Collecting System ... via ProtocolEnum.REDFISH...\n2018-07-26 08:00:23,709 - DEBUG - urllib3.connectionpool:823 - Starting new HTTPS connection (1): 10.9.245.120:443\n", "msg": "MODULE FAILURE", "rc": 1}
fatal: [10.9.245.154]: FAILED! => {"changed": false, "msg": "returned status code doesn't match with the expected success code"}
fatal: [10.9.245.197]: FAILED! => {"changed": false, "msg": "returned status code doesn't match with the expected success code"}

**Comment by LangeshDharmalingam** [comment]
Hi Feisa,
 Thankyou to write to us. We will help you to fix the issue

Need following information to debug better:
- Ansible Version
- Server Model
- iDRAC Firmware version

By the way above playbook is partial. We do support nfs share path or local path. If you want to use nfs fileshare provide share_name, share_mnt, share_user & share_pwd or incase of local share_name along is good.

**Comment by feisa** [comment]
Ansible Version 
ansible 2.6.1
  config file = /home/feisa/git/network/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

Ansible Server Model
Dell r620 and Dell r630

Idrac firmware
2.52.52.52
--

Playbook 
---
- name: idrac ntp configuration 
  hosts: idracs
  gather_facts: false
  connection: local
  tasks:
  - name: setting anycast ntp
    dellemc_configure_idrac_timezone:
     idrac_ip: 10.9.245.120 
     idrac_user: root
     idrac_pwd: *******
     share_name: /mnt/research/feisa-mount-test
     share_mnt: /mnt/research/feisa-mount-test 
     enable_ntp: Enabled
     setup_idrac_timezone: UTC
     ntp_server_1: 10.255.255.2

The share name/mnt are local to my machine and not nfs. I believe they are also required

**Comment by feisa** [comment]
any update on this?

**Comment by rajshekarp87** [comment]
Hi Feisa,

Apologies for delayed response.

We checked this in our lab. Its working fine. If you are using local path, "share_name" is sufficient. No need to use "share_mnt".

Please let us know If you are still facing this issue. Also let us know "Dell EMC Ansible Module" and OMSDK version.

**Comment by rajeevarakkal** [comment]
Hi Feisa,

Are we good with this?

Thanks,
Rajeev

**Comment by feisa** [comment]
Let me retest 

Freddie

**Comment by rajeevarakkal** [comment]
@feisa we are closing this defect as idle for sometime. In case you still facing the issue, please re-open
