### ISSUE TITLE
NameError: name 'LogManager' is not defined

### ISSUE THREAD

**Issue by knaveenr** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#5]
While trying to collect inventory using Ansible module, getting below error. Not sure what is preventing the LogManager import. 

Env:
CentOS7 with Python 2.7.5

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_LbT17e/ansible_module_dellemc_get_system_inventory.py", line 17, in <module>
    from ansible.module_utils.dellemc_idrac import *
  File "/tmp/ansible_LbT17e/ansible_modlib.zip/ansible/module_utils/dellemc_idrac.py", line 32, in <module>
NameError: name 'LogManager' is not defined

fatal: [idrac1 -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_LbT17e/ansible_module_dellemc_get_system_inventory.py\", line 17, in <module>\n    from ansible.module_utils.dellemc_idrac import *\n  File \"/tmp/ansible_LbT17e/ansible_modlib.zip/ansible/module_utils/dellemc_idrac.py\", line 32, in <module>\nNameError: name 'LogManager' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

```
```
# python
Python 2.7.5 (default, Apr  9 2015, 11:03:32)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ansible.module_utils.dellemc_idrac import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ansible/module_utils/dellemc_idrac.py", line 32, in <module>
    LogManager.setup_logging(logger_log_file='/tmp/ansible-omsdk/omsdk_log.log', logger_level=logging.DEBUG)
NameError: name 'LogManager' is not defined
>>>
```

**Comment by anupamaloke** [comment]
LogManager module should have been installed as part of omsdk installation. Could you please check whether you have installed omsdk or not and is available in your PYTHONPATH?

`python -c "from omsdk.sdkinfra import sdkinfra"`

**Comment by vidkun** [comment]
I'm getting pretty much the same error on MacOS with python 2.7.15.
Omsdk 1.1.267 is installed. The command you provided above returns nothing on my machine.

If I run python and then run in the interpretor `from omsdk.omlogs.Logger import LogManager` it executes just fine. Even running it via `python -c` like you listed above completes just fine.

**Comment by rajeevarakkal** [comment]
Could you please check the followings and let us know

- Details of installed omsdk using "pip list | grep omsdk"
- The user which is running ansible playbook has necessary permissions to invoke omsdk modules.
- Do you have multiple pythons instances and any conflicting omsdk versions available on the system




Also, let us know you have multiple python installations

**Comment by vidkun** [comment]
1)
```
$ pip list | grep omsdk 
omsdk              1.1.267
```
2) yes. see [comment above](https://github.com/dell/Dell-EMC-Ansible-Modules-for-iDRAC/issues/5#issuecomment-422429899)
3) There is an instance of python 3 on the box as well, but it does not have omsdk installed. Additionally, all the ansible logging output explicitly shows 2.7 as the python it is using. Also:
```
$ python -V
Python 2.7.15
```

**Comment by rajeevarakkal** [comment]
Even though all the modules including "LogManager" is individually getting imported, during playbook execution import error getting thrown.  This looks bit strange and happens mostly because of some inter module name ambiguity, multiple version of same module or software present or any other similar python conflicts. It will be great if you can try out the following

- Re-install omsdk & dellemc ansible modules (remove the existing one first and fresh install new files)
- Try installing omsdk & dellemc ansible modules on another ansible control machine

In case both of these are not serving the purpose, lets know the feasibility to have a remote troubleshooting session

**Comment by gedia** [comment]
Are you running ansible-playbook inside a virtualenv? In my case, I had to install omsdk system-wide, which got rid of this error (something to do with the connection being local and ansible not copying all dependencies properly, I guess?).

**Comment by rajeevarakkal** [comment]
Please try out our latest 1.0.4 devel branch release. We have discontinued the use of LogManager from this release.

**Comment by rajeevarakkal** [comment]
1.0.4 devel changes has been merged to Master as part latest release version 1.1. With this I am closing the defect. Let us know in case you facing the same difficulty again
