### ISSUE TITLE
Error: Invalid attribute FreeSize

### ISSUE THREAD

**Issue by zlangi** [dell/Dell-EMC-Ansible-Modules-for-iDRAC#6]
When trying to create a new volume group on a Dell PowerEdge R640 with PERC H740P Mini, the creation process fails with the following:

PLAY [Create the RAID] *********************************************************

TASK [Create the RAID] *********************************************************
fatal: [node01]: FAILED! => {"changed": false, "msg": "Error: Invalid attribute FreeSize"}

To reproduce: simply try to create a raid 0 array with a single disk as a test, it will fail with the message above.

**Comment by rajshekarp87** [comment]
Hi,

Can you share below details.

Playbook used used for volume creation
Dell Ansible Module version

Thanks & Regards,
Rajshekar P

**Comment by zlangi** [comment]
Hello,

Dell ansible version I use: v1.0.1-4-g687a717

My playbook looks like this:
---
- hosts: node01
  connection: local
  name: Create the RAID 
  gather_facts: False

  tasks:
  - name: Create the RAID 
    dellemc_configure_raid:
       idrac_ip:   "2.2.2.2"
       idrac_user: "root"
       idrac_pwd:  "xx"
       share_name: "\\\\1.2.3.4\\images\\dell"
       share_user: "dell"
       share_pwd:  "secret"
       share_mnt:  "/mnt-point/dell"
       state: "present"
       vd_name: "raid0"
       controller_fqdd: "RAID.Integrated.1-1"
       raid_level: "RAID 0"
       stripe_size: "262144"
       disk_cache_policy: "Disabled"
       write_cache_policy: "WriteThrough"
       read_cache_policy: "NoReadAhead"
       media_type: "SSD"
       bus_protocol: "SATA"

**Comment by rajshekarp87** [comment]
Hi,

Thanks for sharing required details. We will check this and get back to you.

Thanks & Regards,
Rajshekar P

**Comment by rajshekarp87** [comment]
Hi,

Apologies for delayed response.

We checked the scenario with Dell EMC Ansible Module v1.0.3. No issue observed and volume creation was successful.

Please let us know If you are still facing this issue. Also share below details.
OMSDK version
Ansible version
OS details
Python and PIP version

Thanks & Regards,
Rajshekar P

**Comment by rajeevarakkal** [comment]
Since there is no update sometime now and the original module where issue is reported has been deprecated with "devel" 1.0.3 release, we are closing this defect.
